---
apiVersion: v1
kind: Namespace
metadata:
  name: build

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: buildx-builder
  namespace: build

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: buildx-builder
  namespace: build
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["create", "get", "list", "watch", "update", "delete"]
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["create", "get", "list", "watch", "update", "delete"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create", "get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: buildx-builder
  namespace: build
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: buildx-builder
subjects:
  - kind: ServiceAccount
    name: buildx-builder
    namespace: build

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hook-rollout-restart
  namespace: build
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hook-rollout-restart
  namespace: build
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hook-rollout-restart
subjects:
  - kind: ServiceAccount
    name: buildx-builder
    namespace: build

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hook-config
  namespace: build
data:
  config.toml: |
    [app]
    registry = "registry.nathanwhyte.dev"

    [[projects]]
    name = "Build Hook"
    slug = "hook"

    [projects.code]
    url = "https://github.com/nathanwhyte/build-hook"
    branch = "main"

    [[projects.image]]
    repository = "build-hook/api"
    location = "Dockerfile"
    tag = "latest"

    [projects.deployments]
    namespace = "build"
    resources = ["deployment/hook"]

    [[projects]]
    name = "Credit Coach"
    slug = "coach"

    [projects.code]
    url = "https://github.com/nathanwhyte/credit-coach"
    branch = "main"

    [[projects.image]]
    repository = "coach/coach"
    location = "Dockerfile"
    tag = "release"

    [[projects.image]]
    repository = "coach/scrub"
    location = "scrub/Dockerfile"
    tag = "release"

    [projects.deployments]
    namespace = "coach"
    resources = ["deployment/credit-coach", "deployment/scrub"]

    [[projects]]
    name = "Equal Risk Portfolio Calculator"
    slug = "equal-risk"

    [projects.code]
    url = "https://github.com/nathanwhyte/equal-risk-portfolio"
    branch = "main"

    [[projects.image]]
    repository = "equal-risk/rails"
    location = "Dockerfile"
    tag = "release"

    [[projects.image]]
    repository = "equal-risk/math"
    location = "api/Dockerfile"
    tag = "release"

    [projects.deployments]
    namespace = "equal-risk"
    resources = ["deployment/equal-risk-rails", "deployment/equal-risk-math"]

    [[projects]]
    name = "Portfolio"
    slug = "portfolio"

    [projects.code]
    url = "https://github.com/nathanwhyte/nathanwhyte.dev"
    branch = "main"

    [[projects.image]]
    repository = "portfolio/portfolio"
    location = "Dockerfile"
    tag = "latest"

    [projects.deployments]
    namespace = "portfolio"
    resources = ["deployment/phx"]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hook
  namespace: build
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hook
  template:
    metadata:
      labels:
        app: hook
    spec:
      serviceAccountName: buildx-builder
      containers:
        - name: hook
          image: registry.nathanwhyte.dev/build-hook/api:latest
          ports:
            - containerPort: 3000
              name: http
          imagePullPolicy: Always
          env:
            - name: BEARER_TOKENS
              valueFrom:
                secretKeyRef:
                  name: bearer-tokens-secret
                  key: BEARER_TOKENS
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-access-token
                  key: GITHUB_TOKEN
          volumeMounts:
            - name: config
              mountPath: /app/config.toml
              subPath: config.toml
              readOnly: true
            - name: cache
              mountPath: /cache
            - name: build-context
              mountPath: /build-context
            - name: docker-config
              mountPath: /root/.docker/config.json
              subPath: .dockerconfigjson
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: cache
          hostPath:
            path: /data/build-cache
            type: DirectoryOrCreate
        - name: config
          configMap:
            name: hook-config
        - name: build-context
          hostPath:
            path: /data/build-context
            type: DirectoryOrCreate
        - name: docker-config
          secret:
            secretName: registry-credentials

---
apiVersion: v1
kind: Service
metadata:
  name: hook
  namespace: build
spec:
  type: ClusterIP
  selector:
    app: hook
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tunnel
  namespace: build
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tunnel
  template:
    metadata:
      labels:
        app: tunnel
    spec:
      containers:
        - name: tunnel
          image: cloudflare/cloudflared:latest
          args:
            - tunnel
            - --no-autoupdate
            - run
            - --token-file
            - /etc/cloudflared/token
          volumeMounts:
            - name: tokenfile
              mountPath: /etc/cloudflared
              readOnly: true
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
      volumes:
        - name: tokenfile
          secret:
            secretName: hook-cloudflared-token
            items:
              - key: TOKEN
                path: token
